export const ERROR_CODES = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  NOT_FOUND: 'NOT_FOUND',
  IS_EMAIL: 'IS_EMAIL',
  MIN_LENGTH: 'MIN_LENGTH',
  MAX_LENGTH: 'MAX_LENGTH',
  IS_NOT_EMPTY: 'IS_NOT_EMPTY',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_NOT_ALLOWED: 'FILE_NOT_ALLOWED',
  WHITELIST_VALIDATION: 'WHITELIST_VALIDATION',
  VALIDATE_ERROR: 'VALIDATE_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  DB_CONNECTION_ERROR: 'DB_CONNECTION_ERROR',
  DB_DELETE_ERROR: 'DATBASE_DELETE_ERROR',
  DB_DUPLICATE_ENTRY: 'DB_DUPLICATE_ENTRY',
  DB_FOREIGN_KEY: 'DB_FOREIGN_KEY',
  DB_INVALID_INPUT: 'DB_INVALID_INPUT',
  DB_UNKNOW_ERROR: 'DB_UNKNOW_ERROR',
  DB_UPLOAD_ERROR: 'DATABSE_UPLOAD_ERROR',
  REGISTER_ACCOUNT_ERROR: 'REGISTER_ACCOUNT_ERROR',
  SAVE_TOKEN_ERROR: 'SAVE_TOKEN_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  UNREGISTERED_ERROR: 'UNREGISTERED_ERROR',
  CAN_NOT_READ_DIMENSION: 'CAN_NOT_READ_DIMENSION',
  INVALID_RASIO_AVATAR: 'INVALID_RASIO_AVATAR',
  UNREADABLE_FILE: 'UNREADABLE_FILE',
};



export type ErrorCode = keyof typeof ERROR_CODES;
